const HotProduct = [
    {
        id: 1,
        img: "https://tocotocotea.com/wp-content/uploads/2022/10/sua-chua-man-hat-sen-.png",
        title: "Sữa Chua Mận Hạt Sen",
        price: 31000,
        oldPrice: "48000đ",
    },
    {
        id: 2,
        img: "https://tocotocotea.com/wp-content/uploads/2022/10/tra-man-hat-sen.png",
        title: "Trà Mận Hạt Sen",
        price: 31000,
        oldPrice: "48000đ",
    },
    {
        id: 3,
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/O-Long-xoai-kem-coffee.jpg",
        title: "Ô Lông Xoài Kem Coffee",
        price: 31000,
        oldPrice: "49000đ",
    },
    {
        id: 4,
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/Tra-dao-buoi-hong-tran-chau-baby.jpg",
        title: "Trà Đào Bưởi Hồng Trân Châu Baby",
        price: 31000,
        oldPrice: "38000đ",
    },
    {
        id: 5,
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/6ly_hong.png",
        title: "Instant Milk Tea - Strawberry - Set 6 Ly",
        price: 165000,
    },
    {
        id: 6,
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/6ly_vang.png",
        title: "Instant Milk Tea - Original - Set 6 ly",
        price: 160000,
    },
    {
        id: 7,
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/Stawberry-Milk-Tea.jpg",
        title: "Instant Milk Tea - Strawberry",
        price: 26000,
    },
    {
        id: 8,
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/Original-Milk-Tea.jpg",
        title: "Instant Milk Tea - Original",
        price: 25000,
    },
    {
        id: 9,
        img: "https://tocotocotea.com/wp-content/uploads/2022/04/tra%CC%80-xoa%CC%80i-bu%CC%9Bo%CC%9B%CC%89i-ho%CC%82%CC%80ng.png",
        title: "Trà Xoài Bưởi Hồng",
        price: 31000,
        oldPrice: "30,000đ",
    },
    {
        id: 10,
        img: "https://tocotocotea.com/wp-content/uploads/2022/04/tra%CC%80-xoa%CC%80i-bu%CC%9Bo%CC%9B%CC%89i-ho%CC%82%CC%80ng-kem-pho%CC%82-mai.png",
        title: "Trà Xoài Bưởi Hồng Kem Phô Mai",
        price: 31000,
        oldPrice: "40,000đ",
    },
    {
        id: 11,
        img: "https://tocotocotea.com/wp-content/uploads/2021/12/Hi%CC%80nh-a%CC%89nh-sp-website_1000x1000_choco-ngu%CC%83-co%CC%82%CC%81c-kem-cafe.png",
        title: "Choco Ngũ Cốc Kem Cafe",
        price: 31000,
        oldPrice: "44,000đ",
    },
    {
        id: 12,
        img: "https://tocotocotea.com/wp-content/uploads/2021/12/Hi%CC%80nh-a%CC%89nh-sp-website_1000x1000_ho%CC%82%CC%80ng-tra%CC%80-ngu%CC%83-co%CC%82%CC%81c-kem-cafe.png",
        title: "Hồng Trà Ngũ Cốc Kem Cafe",
        price: 31000,
        oldPrice: "44,000đ",
    },
    {
        id: 13,
        img: "https://tocotocotea.com/wp-content/uploads/2021/11/Royal-Pearl-Milk-Coffee.png",
        title: "Royal Pearl Milk Coffee",
        price: 31000,
        oldPrice: "30,000đ",
    },
    {
        id: 14,
        img: "https://tocotocotea.com/wp-content/uploads/2021/11/Grass-Jelly-Milk-Coffee.png",
        title: "Grass Jelly Milk Coffee",
        price: 22000,
        oldPrice: "30,000đ",
    },
    {
        id: 15,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/ezgif.com-gif-maker-12.jpg",
        title: "Tiger Sugar",
        price: 22000,
        oldPrice: "52,000đ",
    },
    {
        id: 16,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Tran-Chau-Hoang-Gia-1-copy.jpg",
        title: "Trà Sữa Trân Châu Hoàng Gia",
        price: 31000,
        oldPrice: "46,000đ",
    },
    {
        id: 17,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Ba-Anh-Em-1-copy.jpg",
        title: "Trà Sữa Ba Anh Em",
        price: 31000,
        oldPrice: "40,000đ",
    },
    {
        id: 18,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Panda-1-copy.jpg",
        title: "Trà Sữa Panda",
        price: 31000,
        oldPrice: "40,000đ",
    },
    {
        id: 19,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Kim-Cuong-Den-Okinawa-2-copy.jpg",
        title: "Trà Sữa Kim Cương Đen Okinawa",
        price: 31000,
        oldPrice: "46,000đ",
    },
    {
        id: 20,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/oolong-kem-pho-mai_75e8d3f11fb3402196416da77c8ff33a_grande.png",
        title: "Ô Long Kem Phô Mai",
        price: 31000,
        oldPrice: "44,000đ",
    },
    {
        id: 21,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Dua-Nhiet-Doi-2-copy.jpg",
        title: "Trà dứa nhiệt đới",
        price: 31000,
        oldPrice: "30,000đ",
    },
    {
        id: 22,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Hanh-Phuc-1-copy.jpg",
        title: "Trà Sữa Hạnh Phúc",
        price: 31000,
        oldPrice: "46,000đ",
    },
];

const MilkTea = [
    {
        id: 23,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/ezgif.com-gif-maker-6.jpg",
        title: "Ô long Trân châu Baby Kem Café",
        price: 31000,
        oldPrice: "49,000đ",
    },
    {
        id: 24,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Xanh-2-copy.jpg",
        title: "Trà Xanh",
        price: 31000,
        oldPrice: "32,000đ",
    },
    {
        id: 25,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/ezgif.com-gif-maker-6.jpg",
        title: "Sữa Tươi Trân Châu Baby Kem Café",
        price: 31000,
        oldPrice: "49,000đ",
    },
    {
        id: 26,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/ezgif.com-gif-maker-15.jpg",
        title: "Trà Xanh Sữa Vị Nhài",
        price: 31000,
        oldPrice: "38,000đ",
    },
    {
        id: 27,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Matcha-1-copy.jpg",
        title: "Trà Sữa Matcha",
        price: 31000,
        oldPrice: "40,000đ",
    },
    {
        id: 28,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-O-Long-Sua-2-copy.jpg",
        title: "Trà Sữa Ô Long",
        price: 31000,
        oldPrice: "39,000đ",
    },
    {
        id: 29,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/O-Long-Thai-Cuc-2-copy.jpg",
        title: "Ô Long Thái Cực",
        price: 31000,
        oldPrice: "45,000đ",
    },
    {
        id: 30,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Hong-Tra-2-copy.jpg",
        title: "Hồng Trà",
        price: 31000,
        oldPrice: "32,000đ",
    },
    {
        id: 31,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/ezgif.com-gif-maker-11.jpg",
        title: "Matcha Đậu Đỏ",
        price: 31000,
        oldPrice: "49,000đ",
    },
    {
        id: 32,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Socola-1-copy.jpg",
        title: "Trà Sữa Socola",
        price: 31000,
        oldPrice: "40,000đ",
    },
    {
        id: 33,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Bac-Ha-2-copy.jpg",
        title: "Trà sữa dâu tây",
        price: 31000,
        oldPrice: "40,000đ",
    },
    {
        id: 34,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Dau-Tay-2-copy.jpg",
        title: "Trà sữa dâu tây",
        price: 31000,
        oldPrice: "40,000đ",
    },
    {
        id: 35,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-1-copy.jpg",
        title: "Trà sữa",
        price: 31000,
        oldPrice: "38,000đ",
    },
];

const FruitTea = [
    {
        id: 36,
        img: "https://tocotocotea.com/wp-content/uploads/2022/10/tra-man-hat-sen.png",
        title: "Trà Mận Hạt Sen",
        price: 31000,
        oldPrice: "48,000đ",
    },
    {
        id: 37,
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/O-Long-xoai-kem-coffee.jpg",
        title: "Ô Long Xoài Kem Cà Phê",
        price: 31000,
        oldPrice: "49,000đ",
    },
    {
        id: 38,
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/Tra-dao-buoi-hong-tran-chau-baby.jpg",
        title: "Trà Đào Bưởi Hồng Trân Châu Baby",
        price: 31000,
        oldPrice: "38,000đ",
    },
    {
        id: 39,
        img: "https://tocotocotea.com/wp-content/uploads/2022/04/tra%CC%80-xoa%CC%80i-bu%CC%9Bo%CC%9B%CC%89i-ho%CC%82%CC%80ng.png",
        title: "Trà Xoài Bưởi Hồng",
        price: 31000,
        oldPrice: "38,000đ",
    },
    {
        id: 40,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/ezgif.com-gif-maker-2.jpg",
        title: "Probi Bưởi Trân Châu Sương Mai",
        price: 31000,
        oldPrice: "42,000đ",
    },
    {
        id: 41,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/ezgif.com-gif-maker-3.jpg",
        title: "Probi Xoài Trân Châu Sương Mai",
        price: 31000,
        oldPrice: "42,000đ",
    },
    {
        id: 42,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/tra_xanh_xoai_35d69664c31248faaf3eeade044035ba_grande.jpg",
        title: "Trà Xanh Xoài",
        price: 31000,
        oldPrice: "38,000đ",
    },
    {
        id: 43,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Dau-Tam-Pha-Le-Tuyet-2-copy.jpg",
        title: "Trà dâu tằm pha lê tuyết",
        price: 31000,
        oldPrice: "42,000đ",
    },
    {
        id: 44,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/ezgif.com-gif-maker-7.jpg",
        title: "Hồng Trà Bưởi Mật Ong",
        price: 31000,
        oldPrice: "42,000đ",
    },
];

const Macchiato = [
    {
        id: 45,
        img: "https://tocotocotea.com/wp-content/uploads/2022/04/tra%CC%80-xoa%CC%80i-bu%CC%9Bo%CC%9B%CC%89i-ho%CC%82%CC%80ng-kem-pho%CC%82-mai.png",
        title: "Trà Xoài Bưởi Hồng Kem Phô Mai",
        price: 31000,
        oldPrice: "48,000đ",
    },
    {
        id: 46,
        img: "https://tocotocotea.com/wp-content/uploads/2021/12/Hi%CC%80nh-a%CC%89nh-sp-website_1000x1000_choco-ngu%CC%83-co%CC%82%CC%81c-kem-cafe.png",
        title: "Choco Ngũ Cốc Kem Cafe",
        price: 31000,
        oldPrice: "44,000đ",
    },
    {
        id: 47,
        img: "https://tocotocotea.com/wp-content/uploads/2021/12/Hi%CC%80nh-a%CC%89nh-sp-website_1000x1000_ho%CC%82%CC%80ng-tra%CC%80-ngu%CC%83-co%CC%82%CC%81c-kem-cafe.png",
        title: "Hồng Trà Ngũ Cốc Kem Cafe",
        price: 31000,
        oldPrice: "44,000đ",
    },
    {
        id: 48,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Dau-Tam-Kem-Pho-Mai-2-copy.jpg",
        title: "Dâu Tằm Kem Phô Mai",
        price: 31000,
        oldPrice: "48,000đ",
    },
    {
        id: 49,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Hong-Tra-Kem-Pho-Mai-2-copy.jpg",
        title: "Hồng Trà Kem Phô Mai",
        price: 31000,
        oldPrice: "42,000đ",
    },
    {
        id: 50,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Xanh-Kem-Pho-Mai-2-copy.jpg",
        title: "Trà Xanh Kem Phô Mai",
        price: 31000,
        oldPrice: "40,000đ",
    },
    {
        id: 51,
        img: "https://tocotocotea.com/wp-content/uploads/2021/01/matcha-kem-pho-mai_09b3b54997614aea86d2b61bcd7f548c_73a9e7cd539949718b13b06c5db9522f_grande.png",
        title: "Matcha Kem Phô Mai",
        price: 31000,
        oldPrice: "48,000đ",
    },
];

const Yogurt = [
    {
        id: 52,
        img: "https://tocotocotea.com/wp-content/uploads/2022/10/sua-chua-man-hat-sen-.png",
        title: "Sữa Chua Mận Hạt Sen",
        price: 31000,
        oldPrice: "48,000đ",
    },
    {
        id: 53,
        img: "https://tocotocotea.com/wp-content/uploads/2021/05/sua-chua-dau-tam-hoang-kim.png",
        title: "Sữa Chua Dâu Tằm Hoàng Kim",
        price: 31000,
        oldPrice: "39,000đ",
    },
    {
        id: 54,
        img: "https://tocotocotea.com/wp-content/uploads/2021/05/sua-chua-dau-tam-hat-de-.png",
        title: "Sữa Chua Dâu Tằm Hạt Dẻ",
        price: 31000,
        oldPrice: "42,000đ",
    },
    {
        id: 55,
        img: "https://tocotocotea.com/wp-content/uploads/2021/05/sua-chua-trang-.png",
        title: "Sữa Chua Trắng",
        price: 31000,
        oldPrice: "32,000đ",
    },
];

export { HotProduct, MilkTea, FruitTea, Macchiato, Yogurt };
