export const HotProductsData = [
    {
        id: 1,
        newTag: "new",
        discountTag: "35%",
        img: "https://tocotocotea.com/wp-content/uploads/2022/10/sua-chua-man-hat-sen-.png",
        title: "Sữa Chua Mận Hạt Sen",
        price: 31000,
        oldPrice: "48000đ",
    },
    {
        id: 2,
        newTag: "new",
        discountTag: "35%",
        img: "https://tocotocotea.com/wp-content/uploads/2022/10/tra-man-hat-sen.png",
        title: "Trà Mận Hạt Sen",
        price: 31000,
        oldPrice: "48000đ",
    },
    {
        id: 3,
        newTag: "new",
        discountTag: "37%",
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/O-Long-xoai-kem-coffee.jpg",
        title: "Ô Lông Xoài Kem Coffee",
        price: 31000,
        oldPrice: "49000đ",
    },
    {
        id: 4,
        newTag: "new",
        discountTag: "18%",
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/Tra-dao-buoi-hong-tran-chau-baby.jpg",
        title: "Trà Đào Bưởi Hồng Trân Châu Baby",
        price: 31000,
        oldPrice: "38000đ",
    },
    {
        id: 5,
        newTag: "new",
        discountTag: "",
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/6ly_hong.png",
        title: "Instant Milk Tea - Strawberry - Set 6 Ly",
        price: 165000,
    },
    {
        id: 6,
        newTag: "new",
        discountTag: "",
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/6ly_vang.png",
        title: "Instant Milk Tea - Original - Set 6 ly",
        price: 160000,
    },
    {
        id: 7,
        newTag: "new",
        discountTag: "",
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/Stawberry-Milk-Tea.jpg",
        title: "Instant Milk Tea - Strawberry",
        price: 26000,
    },
    {
        id: 8,
        newTag: "new",
        discountTag: "",
        img: "https://tocotocotea.com/wp-content/uploads/2022/06/Original-Milk-Tea.jpg",
        title: "Instant Milk Tea - Original",
        price: 25000,
    },
];
